const canvas = document.getElementById('game');
const ctx = canvas.getContext('2d');
const startScreen = document.getElementById('start-screen');
const gameOverScreen = document.getElementById('game-over');
const startButton = document.getElementById('start-button');
const restartButton = document.getElementById('restart-button');
const distanceReadout = document.getElementById('distance');
const speedReadout = document.getElementById('speed');
const missesReadout = document.getElementById('near-misses');
const focusBar = document.getElementById('focus-bar');
const bestDistanceReadout = document.getElementById('best-distance');
const finalDistanceReadout = document.getElementById('final-distance');
const bikerImages = ['assets/biker-red.svg', 'assets/biker-yellow.svg', 'assets/biker-blue.svg'].map((src) => { const image = new Image(); image.src = src; return image; });

const state = { running:false, over:false, distance:0, speed:0, targetSpeed:0, lane:1, riderX:0, roadOffset:0, spawnTimer:0, nearMisses:0, focus:100, traffic:[], lastTime:0, best:Number(localStorage.getItem('night-shift-best') || 0) };
const keys = { left:false, right:false, brake:false };

function resize() { const rect = canvas.getBoundingClientRect(); const dpr = Math.min(window.devicePixelRatio || 1, 2); canvas.width = rect.width * dpr; canvas.height = rect.height * dpr; ctx.setTransform(dpr,0,0,dpr,0,0); }
function W() { return canvas.clientWidth; } function H() { return canvas.clientHeight; }
function roadBounds() { return { horizon:H()*.29, center:W()*.5, bottomLeft:W()*.03, bottomRight:W()*.97 }; }
function roadWidthAt(y) { const road = roadBounds(); return 18 + (road.bottomRight-road.bottomLeft) * Math.pow(Math.max(0,Math.min(1,(y-road.horizon)/(H()-road.horizon))), .82); }
function laneX(lane, y = H()*.78) { const road = roadBounds(); return road.center + (lane - 1) * roadWidthAt(y) / 3; }
function perspectiveY(y) { return Math.max(0, Math.min(1, (y-roadBounds().horizon)/(H()-roadBounds().horizon))); }
function reset() { state.distance=0; state.speed=0; state.targetSpeed=0; state.lane=1; state.riderX=laneX(1); state.roadOffset=0; state.spawnTimer=0; state.nearMisses=0; state.focus=100; state.traffic=[]; state.over=false; }
function start() { reset(); state.running=true; startScreen.classList.add('is-hidden'); gameOverScreen.classList.add('is-hidden'); state.lastTime=performance.now(); requestAnimationFrame(loop); }
function endGame() { state.running=false; state.over=true; const meters=Math.floor(state.distance); if(meters>state.best){state.best=meters; localStorage.setItem('night-shift-best', meters);} finalDistanceReadout.textContent=String(meters).padStart(4,'0'); bestDistanceReadout.textContent=String(state.best).padStart(4,'0')+' m'; gameOverScreen.classList.remove('is-hidden'); }
function drawBackground() { const w=W(),h=H(),horizon=roadBounds().horizon; const sky=ctx.createLinearGradient(0,0,0,horizon); sky.addColorStop(0,'#050b15'); sky.addColorStop(.62,'#16364b'); sky.addColorStop(1,'#c97850'); ctx.fillStyle=sky; ctx.fillRect(0,0,w,horizon+8); ctx.fillStyle='#07111b'; for(let i=0;i<18;i++){const x=(i*97+17)%w, height=18+(i*23)%75; ctx.fillRect(x,horizon-height,28+(i%3)*15,height);} ctx.fillStyle='#f6b36c';ctx.globalAlpha=.45;ctx.beginPath();ctx.arc(w*.72,horizon*.77,18,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1; }
function drawRoad() { const w=W(),h=H(),r=roadBounds(); ctx.fillStyle='#102c28';ctx.fillRect(0,r.horizon,w,h-r.horizon); ctx.fillStyle='#20272c';ctx.beginPath();ctx.moveTo(r.center-9,r.horizon);ctx.lineTo(r.bottomLeft,h);ctx.lineTo(r.bottomRight,h);ctx.lineTo(r.center+9,r.horizon);ctx.closePath();ctx.fill(); ctx.strokeStyle='#d5a74d';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(r.center-9,r.horizon);ctx.lineTo(r.bottomLeft+3,h);ctx.moveTo(r.center+9,r.horizon);ctx.lineTo(r.bottomRight-3,h);ctx.stroke(); for(let lane=1;lane<3;lane++){for(let i=0;i<9;i++){const p=(i/9+((state.roadOffset*.001)%1));const y=r.horizon+p*p*(h-r.horizon);const x=r.center+(lane-1.5)*roadWidthAt(y)/3;const dash=2+p*15;ctx.fillStyle='rgba(224,231,215,.8)';ctx.fillRect(x-dash/2,y,dash,Math.max(2,p*12));}} ctx.strokeStyle='rgba(240,170,100,.15)';ctx.lineWidth=1;for(let i=0;i<10;i++){const y=r.horizon+Math.pow(i/10,2)*(h-r.horizon);ctx.beginPath();ctx.moveTo(r.center-roadWidthAt(y)/2,y);ctx.lineTo(r.center+roadWidthAt(y)/2,y);ctx.stroke();} }
function drawVehicle(vehicle) { const y=vehicle.y, depth=.22+perspectiveY(y)*1.1, x=laneX(vehicle.lane,y), width=74*depth, height=118*depth, image=bikerImages[vehicle.biker]; if(!image.complete)return; ctx.save();ctx.globalAlpha=Math.min(1,depth+0.15);ctx.shadowColor='rgba(0,0,0,.65)';ctx.shadowBlur=12*depth;ctx.drawImage(image,x-width/2,y-height*.88,width,height);ctx.restore(); }
function drawBike(x,y) { const image=bikerImages[2]; if(!image.complete)return;ctx.save();ctx.shadowColor='rgba(65,240,208,.55)';ctx.shadowBlur=22;ctx.drawImage(image,x-58,y-157,116,183);ctx.restore(); }
function spawnTraffic() { const lane=Math.floor(Math.random()*3); if(state.traffic.some(v=>v.lane===lane&&v.y<roadBounds().horizon+125)) return; state.traffic.push({lane,y:roadBounds().horizon+4,biker:Math.floor(Math.random()*3),speed:80+Math.random()*70,passed:false}); }
function update(dt) { const road=roadBounds(); state.targetSpeed=keys.brake?100:285; state.speed += (state.targetSpeed-state.speed)*dt*2.2; state.distance += state.speed*dt*.028; state.roadOffset += state.speed*dt*.8; const steer=(keys.right?1:0)-(keys.left?1:0); state.riderX += steer*W()*.85*dt; state.riderX=Math.max(road.center-roadWidthAt(H()*.82)*.43,Math.min(road.center+roadWidthAt(H()*.82)*.43,state.riderX)); state.lane=Math.max(0,Math.min(2,Math.round((state.riderX-road.center)/(roadWidthAt(H()*.82)/3)+1))); state.spawnTimer-=dt; if(state.spawnTimer<=0){spawnTraffic();state.spawnTimer=.62+Math.random()*.7;} for(const vehicle of state.traffic){vehicle.y+=(state.speed-vehicle.speed)*dt*.72; if(!vehicle.passed&&vehicle.y>H()*.73){vehicle.passed=true;state.nearMisses++;state.focus=Math.min(100,state.focus+7);} } state.traffic=state.traffic.filter(v=>v.y<H()+120); for(const vehicle of state.traffic){ if(Math.abs(laneX(vehicle.lane,vehicle.y)-state.riderX)<34&&Math.abs(vehicle.y-(H()*.78))<48){endGame();return;} } state.focus=Math.max(0,state.focus-dt*1.8); }
function render() { drawBackground();drawRoad(); [...state.traffic].sort((a,b)=>a.y-b.y).forEach(drawVehicle); drawBike(state.riderX,H()*.78); distanceReadout.textContent=String(Math.floor(state.distance)).padStart(4,'0'); speedReadout.textContent=String(Math.floor(state.speed)).padStart(3,'0'); missesReadout.textContent=String(state.nearMisses).padStart(2,'0'); focusBar.style.width=state.focus+'%'; }
function loop(now) { if(!state.running)return; const dt=Math.min((now-state.lastTime)/1000,.05);state.lastTime=now;update(dt);render();if(state.running)requestAnimationFrame(loop); }
function setKey(code,pressed){if(code==='ArrowLeft'||code==='KeyA')keys.left=pressed;if(code==='ArrowRight'||code==='KeyD')keys.right=pressed;if(code==='Space')keys.brake=pressed;if(pressed&&code==='Space'&&!state.running)start();}
window.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();setKey(e.code,true);});window.addEventListener('keyup',e=>setKey(e.code,false));
let touchX=0;canvas.addEventListener('touchstart',e=>{touchX=e.touches[0].clientX;},{passive:true});canvas.addEventListener('touchmove',e=>{const delta=e.touches[0].clientX-touchX;keys.left=delta<-12;keys.right=delta>12;touchX=e.touches[0].clientX;},{passive:true});canvas.addEventListener('touchend',()=>{keys.left=false;keys.right=false;},{passive:true});
startButton.addEventListener('click',start);restartButton.addEventListener('click',start);window.addEventListener('resize',()=>{resize();if(!state.running) {state.riderX=laneX(1);render();}}); resize(); bestDistanceReadout.textContent=String(state.best).padStart(4,'0')+' m'; state.riderX=laneX(1);render();
